# Generated by Django 5.2.1 on 2025-05-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preis', models.FloatField()),
                ('rabatt', models.CharField(max_length=20)),
                ('sterne', models.CharField(max_length=20)),
                ('sterneAnzahl', models.IntegerField()),
                ('produktUrl', models.CharField(max_length=300)),
                ('imageUrl', models.CharField(max_length=300)),
            ],
        ),
    ]
