# Generated by Django 5.2.1 on 2025-05-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperdata',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='preis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='produktUrl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='rabatt',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='sterne',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='sterneAnzahl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
