# Generated by Django 5.2.1 on 2025-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0002_alter_scraperdata_imageurl_alter_scraperdata_preis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperdata',
            name='preis',
        ),
        migrations.AddField(
            model_name='scraperdata',
            name='aktuellerPreis',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='scraperdata',
            name='vorherigerPreis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='imageUrl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='produktUrl',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='rabatt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='sterne',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='scraperdata',
            name='sterneAnzahl',
            field=models.IntegerField(null=True),
        ),
    ]
