# Generated by Django 5.2.1 on 2025-06-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0003_remove_scraperdata_preis_scraperdata_aktuellerpreis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperdata',
            name='sterneAnzahl',
        ),
    ]
