# Generated by Django 5.2.1 on 2025-06-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0004_remove_scraperdata_sterneanzahl'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markt', models.CharField(max_length=50)),
                ('maxProducts', models.IntegerField()),
            ],
        ),
    ]
