# Generated by Django 5.2.1 on 2025-06-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0005_maxvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaxValues',
        ),
    ]
