# Generated by Django 5.2.1 on 2025-06-16 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0006_delete_maxvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraperdata',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
