# Generated by Django 5.2.4 on 2025-07-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0008_productdetails_saturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails_otto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.JSONField()),
            ],
        ),
    ]
